# 0.AVISO

O objetivo desse projeto é poder praticar exercitar o conteúdo abordado no meu curso de pós-graduação, sobretudo, visão computacional. Portanto, investirei pouco tempo analisando as variáveis e focarei muito mais em entender a distribuição das imagens.

# 1.Setup

In [1]:
import pandas as pd
import polars as pl
import polars.selectors as cs
from scipy.stats import chi2_contingency, mannwhitneyu

import numpy as np

import altair as alt

from collections import Counter

from util import funcoes_exploracao as fe  # funcoes que criei

from sc_detect.config import RAW_DATA_DIR

2026-10-23 10:11:08.377 | INFO     | sc_detect.config:<module>:11 - PROJ_ROOT path is: /home/gabriel_santiago/Estudos/Portfolio/skin_cancer_detection

In [2]:
# definindo a seed
pl.set_random_seed(42)

In [3]:
# configuracoes altair
alt.renderers.enable("default")
alt.data_transformers.enable("vegafusion", max_rows=None)
alt.theme.enable("fivethirtyeight")

ThemeRegistry.enable('fivethirtyeight')

# 0.Pequeno Teste

Vou testar Polars ao invés de Pandas pela primeira vez, então, aproveitarei para fazer algumas comparações simples e rápidas.

In [4]:
train_metadados_pd = pd.read_csv(RAW_DATA_DIR / 'train-metadata.csv')

/tmp/ipykernel_7444/100571722.py:1: DtypeWarning: Columns (51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  train_metadados_pd = pd.read_csv(RAW_DATA_DIR / 'train-metadata.csv')

In [5]:
train_metadados = pl.read_csv(RAW_DATA_DIR / 'train-metadata.csv')

In [6]:
train_metadados_pd.head()

,isic_id,target,patient_id,age_approx,sex,anatom_site_general,clin_size_long_diam_mm,image_type,tbp_tile_type,tbp_lv_A,...,lesion_id,iddx_full,iddx_1,iddx_2,iddx_3,iddx_4,iddx_5,mel_mitotic_index,mel_thick_mm,tbp_lv_dnn_lesion_confidence
0,ISIC_0015670,0,IP_1235828,60.0,male,lower extremity,3.04,TBP tile: close-up,3D: white,20.244422,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,97.517282
1,ISIC_0015845,0,IP_8170065,60.0,male,head/neck,1.10,TBP tile: close-up,3D: white,31.712570,...,IL_6727506,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,3.141455
2,ISIC_0015864,0,IP_6724798,60.0,male,posterior torso,3.40,TBP tile: close-up,3D: XP,22.575830,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,99.804040
3,ISIC_0015902,0,IP_4111386,65.0,male,anterior torso,3.22,TBP tile: close-up,3D: XP,14.242329,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,99.989998
4,ISIC_0024200,0,IP_8313778,55.0,male,anterior torso,2.73,TBP tile: close-up,3D: white,24.725520,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,70.442510

In [7]:
train_metadados.head()

shape: (5, 55)
┌────────────┬────────┬────────────┬────────────┬───┬────────┬────────────┬────────────┬───────────┐
│ isic_id    ┆ target ┆ patient_id ┆ age_approx ┆ … ┆ iddx_5 ┆ mel_mitoti ┆ mel_thick_ ┆ tbp_lv_dn │
│ ---        ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---    ┆ c_index    ┆ mm         ┆ n_lesion_ │
│ str        ┆ i64    ┆ str        ┆ str        ┆   ┆ str    ┆ ---        ┆ ---        ┆ confidenc │
│            ┆        ┆            ┆            ┆   ┆        ┆ str        ┆ str        ┆ e         │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ f64       │
╞════════════╪════════╪════════════╪════════════╪═══╪════════╪════════════╪════════════╪═══════════╡
│ ISIC_00156 ┆ 0      ┆ IP_1235828 ┆ 60         ┆ … ┆        ┆            ┆ NA         ┆ 97.517282 │
│ 70         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_8170065 ┆ 60         ┆ … ┆        ┆            ┆ NA         ┆ 3.141455  │
│ 45         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_6724798 ┆ 60         ┆ … ┆        ┆            ┆ NA         ┆ 99.80404  │
│ 64         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00159 ┆ 0      ┆ IP_4111386 ┆ 65         ┆ … ┆        ┆            ┆ NA         ┆ 99.989998 │
│ 02         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00242 ┆ 0      ┆ IP_8313778 ┆ 55         ┆ … ┆        ┆            ┆ NA         ┆ 70.44251  │
│ 00         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
└────────────┴────────┴────────────┴────────────┴───┴────────┴────────────┴────────────┴───────────┘

In [8]:
tam_polars = train_metadados.estimated_size() / (1024 ** 2)
print(f"RAM consumida pelo DataFrame no Polars: {tam_polars:.2f} MB")

RAM consumida pelo DataFrame no Polars: 169.83 MB

In [9]:
tam_pandas = train_metadados_pd.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"RAM consumida pelo DataFrame no Pandas: {tam_pandas:.2f} MB")

RAM consumida pelo DataFrame no Pandas: 511.97 MB

Uma diferença um tanto quanto ignorante.

In [10]:
# limpando a memoria
del tam_pandas, train_metadados_pd

# 2.EDA

In [11]:
# vou testar o metodo lazy do polars nesse projeto
train_metadados = pl.scan_csv(
    RAW_DATA_DIR / 'train-metadata.csv',
    null_values = ["", "NA", "NAN", "N/A", "null", "None"])

## 2.1.Visão Geral

In [12]:
train_metadados.head().collect()

shape: (5, 55)
┌────────────┬────────┬────────────┬────────────┬───┬────────┬────────────┬────────────┬───────────┐
│ isic_id    ┆ target ┆ patient_id ┆ age_approx ┆ … ┆ iddx_5 ┆ mel_mitoti ┆ mel_thick_ ┆ tbp_lv_dn │
│ ---        ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---    ┆ c_index    ┆ mm         ┆ n_lesion_ │
│ str        ┆ i64    ┆ str        ┆ i64        ┆   ┆ str    ┆ ---        ┆ ---        ┆ confidenc │
│            ┆        ┆            ┆            ┆   ┆        ┆ str        ┆ str        ┆ e         │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ f64       │
╞════════════╪════════╪════════════╪════════════╪═══╪════════╪════════════╪════════════╪═══════════╡
│ ISIC_00156 ┆ 0      ┆ IP_1235828 ┆ 60         ┆ … ┆ null   ┆ null       ┆ null       ┆ 97.517282 │
│ 70         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_8170065 ┆ 60         ┆ … ┆ null   ┆ null       ┆ null       ┆ 3.141455  │
│ 45         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_6724798 ┆ 60         ┆ … ┆ null   ┆ null       ┆ null       ┆ 99.80404  │
│ 64         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00159 ┆ 0      ┆ IP_4111386 ┆ 65         ┆ … ┆ null   ┆ null       ┆ null       ┆ 99.989998 │
│ 02         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00242 ┆ 0      ┆ IP_8313778 ┆ 55         ┆ … ┆ null   ┆ null       ┆ null       ┆ 70.44251  │
│ 00         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
└────────────┴────────┴────────────┴────────────┴───┴────────┴────────────┴────────────┴───────────┘

In [13]:
# qtd linhas do df
qtd_linhas = train_metadados.select(pl.len()).collect().item()
print(f'Número de linhas do dataframe: {qtd_linhas} linhas.')

Número de linhas do dataframe: 401059 linhas.

In [14]:
# contagem de tipos
print('Tipos dos dados: ')
Counter(list(train_metadados.collect_schema().values()))

Tipos dos dados:

Counter({Float64: 33, String: 19, Int64: 3})

In [15]:
print('Distribuicao de nulos do Dataset:')
nulos = fe.pl_dist_nulos(train_metadados)
nulos

Distribuicao de nulos do Dataset:

shape: (10, 3)
┌─────────────────────┬───────────┬───────────────┐
│ variaveis           ┆ qtd_nulos ┆ percent_nulos │
│ ---                 ┆ ---       ┆ ---           │
│ str                 ┆ u32       ┆ f64           │
╞═════════════════════╪═══════════╪═══════════════╡
│ iddx_5              ┆ 401058    ┆ 100.0         │
│ mel_mitotic_index   ┆ 401006    ┆ 99.99         │
│ mel_thick_mm        ┆ 400996    ┆ 99.98         │
│ iddx_4              ┆ 400508    ┆ 99.86         │
│ iddx_3              ┆ 399994    ┆ 99.73         │
│ iddx_2              ┆ 399991    ┆ 99.73         │
│ lesion_id           ┆ 379001    ┆ 94.5          │
│ sex                 ┆ 11517     ┆ 2.87          │
│ anatom_site_general ┆ 5756      ┆ 1.44          │
│ age_approx          ┆ 2798      ┆ 0.7           │
└─────────────────────┴───────────┴───────────────┘

Não irei me aprofundar na análise de nulos para esse projeto, portanto, apenas irei optar por excluir as colunas com mais de 40% dos valores nulos.

In [16]:
# extraindo colunas com muitos nulos
cols_null_drop = (
    nulos
        .filter(pl.col('percent_nulos') >= 40)
        .get_column('variaveis')
        .to_list()
)

print(cols_null_drop)

['iddx_5', 'mel_mitotic_index', 'mel_thick_mm', 'iddx_4', 'iddx_3', 'iddx_2', 'lesion_id']

In [17]:
# estatistica do df
train_metadados.describe()

shape: (9, 56)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ isic_id   ┆ target   ┆ patient_i ┆ … ┆ iddx_5    ┆ mel_mitot ┆ mel_thick ┆ tbp_lv_dn │
│ ---       ┆ ---       ┆ ---      ┆ d         ┆   ┆ ---       ┆ ic_index  ┆ _mm       ┆ n_lesion_ │
│ str       ┆ str       ┆ f64      ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ confidenc │
│           ┆           ┆          ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ e         │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 401059    ┆ 401059.0 ┆ 401059    ┆ … ┆ 1         ┆ 53        ┆ 63        ┆ 401059.0  │
│ null_coun ┆ 0         ┆ 0.0      ┆ 0         ┆ … ┆ 401058    ┆ 401006    ┆ 400996    ┆ 0.0       │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ 0.00098  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 97.162204 │
│ std       ┆ null      ┆ 0.031288 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 8.995782  │
│ min       ┆ ISIC_0015 ┆ 0.0      ┆ IP_000882 ┆ … ┆ Blue      ┆ 0/mm^2    ┆ 0.2       ┆ 1.2611e-1 │
│           ┆ 670       ┆          ┆ 1         ┆   ┆ nevus,    ┆           ┆           ┆ 6         │
│           ┆           ┆          ┆           ┆   ┆ Cellular  ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ 0.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 99.66883  │
│ 50%       ┆ null      ┆ 0.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 99.994588 │
│ 75%       ┆ null      ┆ 0.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 99.99996  │
│ max       ┆ ISIC_9999 ┆ 1.0      ┆ IP_998998 ┆ … ┆ Blue      ┆ >4/mm^2   ┆ 5         ┆ 100.0     │
│           ┆ 967       ┆          ┆ 9         ┆   ┆ nevus,    ┆           ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ Cellular  ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## 2.2.Análises Univariadas

In [18]:
# checando dist da coluna target
fe.pl_contagem_valores(train_metadados, 'target', excluir_na=False).collect()

shape: (2, 3)
┌────────┬────────────┬────────────────┐
│ target ┆ qtd_target ┆ percent_target │
│ ---    ┆ ---        ┆ ---            │
│ i64    ┆ u32        ┆ f64            │
╞════════╪════════════╪════════════════╡
│ 0      ┆ 400666     ┆ 99.9           │
│ 1      ┆ 393        ┆ 0.1            │
└────────┴────────────┴────────────────┘

Temos um problema extremamente desbalanceado.

In [19]:
# checando distribuicao da coluna sex
fe.pl_contagem_valores(train_metadados, 'sex', excluir_na=False).collect()

shape: (3, 3)
┌────────┬─────────┬─────────────┐
│ sex    ┆ qtd_sex ┆ percent_sex │
│ ---    ┆ ---     ┆ ---         │
│ str    ┆ u32     ┆ f64         │
╞════════╪═════════╪═════════════╡
│ null   ┆ 11517   ┆ 2.87        │
│ male   ┆ 265546  ┆ 66.21       │
│ female ┆ 123996  ┆ 30.92       │
└────────┴─────────┴─────────────┘

In [20]:
# describe da idade
df_idade_train = train_metadados.select(pl.col('age_approx'))
df_idade_train.describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ age_approx │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 398261.0   │
│ null_count ┆ 2798.0     │
│ mean       ┆ 58.012986  │
│ std        ┆ 13.596165  │
│ min        ┆ 5.0        │
│ 25%        ┆ 50.0       │
│ 50%        ┆ 60.0       │
│ 75%        ┆ 70.0       │
│ max        ┆ 85.0       │
└────────────┴────────────┘

Temos um coeficiente de variação (std / mean) de aproximadamente 23.5%, o que indica uma alta variabilidade nos dados. Irei plotar um histograma para compreender melhor essa variável, mas espero uma curva a esquerda.

In [21]:
# plotagem
(
    alt.Chart(df_idade_train.collect())
    .mark_bar()
    .encode(
        x=alt.X("age_approx", title="Idade").bin(maxbins=20),
        y=alt.Y("count()", title="Quantidade"),
    )
    .properties(width=600, height=400, title="Distribuição de Idade")
)

alt.Chart(...)

Nossa base de dados está concentrada principalmente no público entre 50 e 70 anos, o que pode enviesar nosso modelo. Ao cruzar essa variável com a target, precisarei verificar seu poder preditivo afim de pensar em como tratar esse problema.

In [22]:
train_metadados.select(pl.all().n_unique()).collect()

shape: (1, 55)
┌─────────┬────────┬────────────┬────────────┬───┬────────┬─────────────┬─────────────┬────────────┐
│ isic_id ┆ target ┆ patient_id ┆ age_approx ┆ … ┆ iddx_5 ┆ mel_mitotic ┆ mel_thick_m ┆ tbp_lv_dnn │
│ ---     ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---    ┆ _index      ┆ m           ┆ _lesion_co │
│ u32     ┆ u32    ┆ u32        ┆ u32        ┆   ┆ u32    ┆ ---         ┆ ---         ┆ nfidence   │
│         ┆        ┆            ┆            ┆   ┆        ┆ u32         ┆ u32         ┆ ---        │
│         ┆        ┆            ┆            ┆   ┆        ┆             ┆             ┆ u32        │
╞═════════╪════════╪════════════╪════════════╪═══╪════════╪═════════════╪═════════════╪════════════╡
│ 401059  ┆ 2      ┆ 1042       ┆ 17         ┆ … ┆ 2      ┆ 8           ┆ 20          ┆ 131480     │
└─────────┴────────┴────────────┴────────────┴───┴────────┴─────────────┴─────────────┴────────────┘

In [23]:
valores_unicos = (
    train_metadados
        .select(pl.all().n_unique())
        .unpivot(variable_name='variaveis', value_name='qtd_valores_unicos')
        .sort('qtd_valores_unicos', descending=False)
    ).collect()
valores_unicos

shape: (55, 2)
┌────────────────────┬────────────────────┐
│ variaveis          ┆ qtd_valores_unicos │
│ ---                ┆ ---                │
│ str                ┆ u32                │
╞════════════════════╪════════════════════╡
│ image_type         ┆ 1                  │
│ target             ┆ 2                  │
│ tbp_tile_type      ┆ 2                  │
│ iddx_5             ┆ 2                  │
│ sex                ┆ 3                  │
│ …                  ┆ …                  │
│ tbp_lv_deltaLBnorm ┆ 396877             │
│ tbp_lv_deltaA      ┆ 398257             │
│ tbp_lv_x           ┆ 398446             │
│ tbp_lv_deltaB      ┆ 398886             │
│ isic_id            ┆ 401059             │
└────────────────────┴────────────────────┘

image_type também pode ser dropada.

In [24]:
train_metadados.select(pl.col('image_type')).unique().collect()

shape: (1, 1)
┌────────────────────┐
│ image_type         │
│ ---                │
│ str                │
╞════════════════════╡
│ TBP tile: close-up │
└────────────────────┘

In [25]:
train_metadados.select(pl.col('tbp_tile_type')).unique().collect()

shape: (2, 1)
┌───────────────┐
│ tbp_tile_type │
│ ---           │
│ str           │
╞═══════════════╡
│ 3D: XP        │
│ 3D: white     │
└───────────────┘

In [26]:
train_metadados.select(pl.col('copyright_license')).unique().collect()

shape: (3, 1)
┌───────────────────┐
│ copyright_license │
│ ---               │
│ str               │
╞═══════════════════╡
│ CC-BY-NC          │
│ CC-BY             │
│ CC-0              │
└───────────────────┘

In [27]:
train_metadados.select(pl.col('attribution')).unique().collect()

shape: (7, 1)
┌─────────────────────────────────┐
│ attribution                     │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Department of Dermatology, Hos… │
│ Memorial Sloan Kettering Cance… │
│ Department of Dermatology, Uni… │
│ ViDIR Group, Department of Der… │
│ ACEMID MIA                      │
│ University Hospital of Basel    │
│ Frazer Institute, The Universi… │
└─────────────────────────────────┘

As variáveis: tbp_lv_x, tbp_lv_y, tbp_lv_z fornecem a posição exata da lesão e isso depende muito da estatura do paciente. 

Para inserir a localização na aprendizagem do modelo, irei trabalhar com outras variáveis, as categóricas: anatom_site_general, tbp_lv_location ou tbp_lv_location_simple.

## 2.3.Data Cleaning

In [28]:
## DROPANDO COLUNAS NULAS E NAO PREDITIVAS
# selecionando as colunas a serem dropadas
columns_to_drop = [
    'tbp_lv_x', 'tbp_lv_y', 'tbp_lv_z',  # vars de posicao  (nao preditivas tambem)
    'attribution', 'copyright_license', 'image_type',  # nao preditivas
    # 'anatom_site_general', 'sex'
      
] + cols_null_drop # nulas

# dropando
df_clean = train_metadados.drop(columns_to_drop)
print(f'Colunas dropadas: {columns_to_drop}')

Colunas dropadas: ['tbp_lv_x', 'tbp_lv_y', 'tbp_lv_z', 'attribution', 'copyright_license', 'image_type', 'iddx_5', 'mel_mitotic_index', 'mel_thick_mm', 'iddx_4', 'iddx_3', 'iddx_2', 'lesion_id']

In [29]:
# calculando quantos registros de target 1 
# perderemos em caso de exclusao de alguns nulos

# calculando qtd de target 1 no dataset de treino
col_nul = ['sex', 'anatom_site_general', 'age_approx']
qtd_target_1_geral = fe.pl_contagem_valores(train_metadados, 'target').filter(pl.col('target') == 1).select('qtd_target').collect().item()

# calculo de perda
for c in col_nul:
    aux = df_clean.filter(~pl.col(c).is_null())
    qtd_target_1_filtrado = (
        fe.pl_contagem_valores(aux, 'target')  # calculando qtd de target 1
            .filter(pl.col('target') == 1)
            .select('qtd_target')
            .collect()
            .item()
        )
    perdidos = qtd_target_1_geral - qtd_target_1_filtrado
    prop_perdidos = perdidos / qtd_target_1_geral
    print(f'Excluindo nulos de {c} perderemos {perdidos} ({prop_perdidos:.2%}) registros de target = 1.')

Excluindo nulos de sex perderemos 10 (2.54%) registros de target = 1.
Excluindo nulos de anatom_site_general perderemos 0 (0.00%) registros de target = 1.
Excluindo nulos de age_approx perderemos 3 (0.76%) registros de target = 1.

Por se tratar de um problema desbalanceado, irei preservar ao máximo a quantidade de registros de target = 1. Portanto, irei preencher sex com a moda e idade com a mediana.

Irei dropar os registros sem anatom_site_general pois pode ser perigoso inferir o local da lesão tanto para o aprendizado do modelo quanto para o paciente.

Para simplificar, usarei apenas sexo, idade e local da lesão para auxiliar na predição.

## 2.3.Analise Bivariada

Quero testar se as variáveis de idade, sexo e local da lesão têm influência direta na target. Para isso, usarei testes estatísticos.

In [30]:
# amostrando para analises
mdt_sample = train_metadados.collect().sample(fraction=0.25)
qtd_linhas = mdt_sample.select(pl.col('target')).count().item()
print(f'Dataframe de treino amostrado em 25% resultou em: {qtd_linhas} linhas.')

Dataframe de treino amostrado em 25% resultou em: 100264 linhas.

### 2.3.1.Variável 'Sex'

In [31]:
# visualizacao da variavel de sexo x target
for t in [0, 1]:
    df_aux = mdt_sample.filter(pl.col('target') == t)
    graf = (
        alt.Chart(df_aux)
        .mark_bar()
        .encode(
            x=alt.X("sex", title="Sexo"),
            y=alt.Y("count()", title="Quantidade"),
        )
        .properties(width=400, height=200, title=f"Distribuição da Target por Sexo = {t}")
    )
    graf.show()

alt.Chart(...)

alt.Chart(...)

A distribuição da target parece ter se mantido entre os sexos, supunho que essa variável não têm relação forte o suficiente com a target. Mas, vamos ao teste.

Para testar essa hipótese, por se tratar de duas variáveis categóricas, escolhi o teste Qui-Quadrado:

* Hipótese Nula (H0): O sexo do paciente e a incidência do tumor (target) são independentes.
* Hipótese Alternativa (H1): O sexo do paciente e a incidência do tumor são dependentes.

In [45]:
# gerando tabela de contingencia
df_contingencia = (
    train_metadados
    .filter(pl.col('sex').is_not_null())
    .group_by("sex")
    .agg([
        (pl.col("target") == 0).sum().alias("benigno"),
        (pl.col("target") == 1).sum().alias("maligno")
    ])
    .sort("sex")
).collect()

# plotando tabela
print("Tabela de Contingência:")
print(df_contingencia)

# executando teste
matriz_frequencias = df_contingencia.select(["benigno", "maligno"]).to_numpy()  # extraindo valores para o teste
chi2, p_valor, dof, esperados = chi2_contingency(matriz_frequencias)

print("\n--- Resultado do Teste Estatístico ---")
print(f"Estatística Chi2: {chi2:.4f}")
print(f"p-valor: {p_valor:.4e}")
print(f"Graus de Liberdade: {dof}")

# interpretacao dos resultados
alpha = 0.05
if p_valor < alpha:
    print("\nConclusão: Rejeitamos H0. Existe uma associação estatisticamente significativa entre 'sex' e 'target'.")
else:
    print("\nConclusão: Falhamos em rejeitar H0. Não há evidência estatística de que 'sex' influencie a 'target'.")

Tabela de Contingência:
shape: (2, 3)
┌────────┬─────────┬─────────┐
│ sex    ┆ benigno ┆ maligno │
│ ---    ┆ ---     ┆ ---     │
│ str    ┆ u32     ┆ u32     │
╞════════╪═════════╪═════════╡
│ female ┆ 123887  ┆ 109     │
│ male   ┆ 265272  ┆ 274     │
└────────┴─────────┴─────────┘

--- Resultado do Teste Estatístico ---
Estatística Chi2: 1.8560
p-valor: 1.7308e-01
Graus de Liberdade: 1

Conclusão: Falhamos em rejeitar H0. Não há evidência estatística de que 'sex' influencie a 'target'.

### 2.3.2.Variável 'age_approx'

In [33]:
# visualizacao da variavel de idade x target
for t in [0, 1]:
    df_aux = mdt_sample.filter(pl.col('target') == t)
    graf = (
        alt.Chart(df_aux)
        .mark_bar()
        .encode(
            x=alt.X("age_approx", title="Idade").bin(maxbins=20),
            y=alt.Y("count()", title="Quantidade"),
        )
        .properties(width=400, height=200, title=f"Distribuição de Idade com Target = {t}")
    )
    graf.show()

alt.Chart(...)

alt.Chart(...)

Já nesse caso, suspeito de que possa haver influência de idade na target.

Para esse teste, irei usar o teste não paramétrico Teste U:
* Hipótese Nula (H0): As distribuições da idade para lesões benignas e malignas são iguais. A idade não tem impacto na probabilidade de malignidade.

* Hipótese Alternativa (H1): As distribuições da idade do grupo com lesões malignas são significativamente diferentes do grupo com lesões benignas.

In [47]:
# agrupando
df_idades = (
    train_metadados
    .filter(pl.col("age_approx").is_not_null())
    .group_by("target")
    .agg(pl.col("age_approx").implode().alias("idades"))
).collect()

# extraindo as dist
idades_benigno = df_idades.filter(pl.col("target") == 0)["idades"].item().to_numpy()
idades_maligno = df_idades.filter(pl.col("target") == 1)["idades"].item().to_numpy()

# executando o teste
stat_u, p_valor_u = mannwhitneyu(idades_maligno, idades_benigno, alternative='two-sided')

# resultados
print(f"Média Idade (Benigno): {idades_benigno.mean():.2f} anos")
print(f"Média Idade (Maligno): {idades_maligno.mean():.2f} anos")
print("-" * 50)
print(f"[Mann-Whitney U]  Estatística: {stat_u:.4f} | p-valor: {p_valor_u:.4e}")

# interpretacao dos resultados
alpha = 0.05
if p_valor < alpha:
    print("\nConclusão: Rejeitamos H0. Existe uma associação estatisticamente significativa entre 'age_approx' e 'target'.")
else:
    print("\nConclusão: Falhamos em rejeitar H0. Não há evidência estatística de que 'age_approx' influencie a 'target'.")

Média Idade (Benigno): 58.01 anos
Média Idade (Maligno): 61.37 anos
--------------------------------------------------
[Mann-Whitney U]  Estatística: 88535852.5000 | p-valor: 1.1996e-06

Conclusão: Rejeitamos H0. Existe uma associação estatisticamente significativa entre 'age_approx' e 'target'.

### 2.3.3.Variável 'anatom_site_general'

In [41]:
# visualizacao da variavel de idade x target
for t in [0, 1]:
    df_aux = mdt_sample.filter(pl.col('target') == t)
    graf = (
        alt.Chart(df_aux)
        .mark_bar()
        .encode(
            x=alt.X("anatom_site_general", title="Local da Lesão"),
            y=alt.Y("count()", title="Quantidade"),
        )
        .properties(width=400, height=200, title=f"Distribuição da Target = {t} com Local da Lesão")
    )
    graf.show()

alt.Chart(...)

alt.Chart(...)

Vejo fortes indícios de que o local da lesão influencia fortemente no diagnóstico.

Para esse teste também irei usar Qui-Quadrado:
* Hipótese Nula (H0): O local anatômico da lesão (anatom_site_general) e a taxa de malignidade (target) são independentes.
* Hipótese Alternativa (H1): A probabilidade da lesão ser maligna varia de acordo com a região do corpo.

In [46]:
# gerando tabela de contingencia
df_contingencia = (
    train_metadados
    .filter(pl.col("anatom_site_general").is_not_null())
    .group_by("anatom_site_general")
    .agg([
        (pl.col("target") == 0).sum().alias("benigno"),
        (pl.col("target") == 1).sum().alias("maligno")
    ])
    .sort("anatom_site_general")
).collect()

# plotando tabela
print("Tabela de Contingência:")
print(df_contingencia)

# executando teste
matriz_frequencias = df_contingencia.select(["benigno", "maligno"]).to_numpy()  # extraindo valores para o teste
chi2, p_valor, dof, esperados = chi2_contingency(matriz_frequencias)

print("\n--- Resultado do Teste Estatístico ---")
print(f"Estatística Chi2: {chi2:.4f}")
print(f"p-valor: {p_valor:.4e}")
print(f"Graus de Liberdade: {dof}")

# interpretacao dos resultados
alpha = 0.05
if p_valor < alpha:
    print("\nConclusão: Rejeitamos H0. Existe uma associação estatisticamente significativa entre 'anatom_site_general' e 'target'.")
else:
    print("\nConclusão: Falhamos em rejeitar H0. Não há evidência estatística de que 'anatom_site_general' influencie a 'target'.")

Tabela de Contingência:
shape: (5, 3)
┌─────────────────────┬─────────┬─────────┐
│ anatom_site_general ┆ benigno ┆ maligno │
│ ---                 ┆ ---     ┆ ---     │
│ str                 ┆ u32     ┆ u32     │
╞═════════════════════╪═════════╪═════════╡
│ anterior torso      ┆ 87688   ┆ 82      │
│ head/neck           ┆ 11968   ┆ 78      │
│ lower extremity     ┆ 102955  ┆ 73      │
│ posterior torso     ┆ 121799  ┆ 103     │
│ upper extremity     ┆ 70500   ┆ 57      │
└─────────────────────┴─────────┴─────────┘

--- Resultado do Teste Estatístico ---
Estatística Chi2: 378.3416
p-valor: 1.3284e-80
Graus de Liberdade: 4

Conclusão: Rejeitamos H0. Existe uma associação estatisticamente significativa entre 'anatom_site_general' e 'target'.