# 1.Setup

In [1]:
import pandas as pd
import polars as pl
import polars.selectors as cs

import numpy as np

import altair as alt

from collections import Counter

from util import funcoes_exploracao as fe  # funcoes que criei

from sc_detect.config import RAW_DATA_DIR

2026-10-20 11:34:01.950 | INFO     | sc_detect.config:<module>:11 - PROJ_ROOT path is: /home/gabriel_santiago/Estudos/Portfolio/skin_cancer_detection

In [2]:
# definindo a seed
pl.set_random_seed(42)

In [3]:
# configuracoes altair
alt.renderers.enable("default")
alt.data_transformers.enable("vegafusion", max_rows=None)
alt.theme.enable("fivethirtyeight")

ThemeRegistry.enable('fivethirtyeight')

# 0.Pequeno Teste

Vou testar Polars ao invés de Pandas pela primeira vez, então, aproveitarei para fazer algumas comparações simples e rápidas.

In [4]:
train_metadados_pd = pd.read_csv(RAW_DATA_DIR / 'train-metadata.csv')

/tmp/ipykernel_22143/100571722.py:1: DtypeWarning: Columns (51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  train_metadados_pd = pd.read_csv(RAW_DATA_DIR / 'train-metadata.csv')

In [5]:
train_metadados = pl.read_csv(RAW_DATA_DIR / 'train-metadata.csv')

In [6]:
train_metadados_pd.head()

,isic_id,target,patient_id,age_approx,sex,anatom_site_general,clin_size_long_diam_mm,image_type,tbp_tile_type,tbp_lv_A,...,lesion_id,iddx_full,iddx_1,iddx_2,iddx_3,iddx_4,iddx_5,mel_mitotic_index,mel_thick_mm,tbp_lv_dnn_lesion_confidence
0,ISIC_0015670,0,IP_1235828,60.0,male,lower extremity,3.04,TBP tile: close-up,3D: white,20.244422,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,97.517282
1,ISIC_0015845,0,IP_8170065,60.0,male,head/neck,1.10,TBP tile: close-up,3D: white,31.712570,...,IL_6727506,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,3.141455
2,ISIC_0015864,0,IP_6724798,60.0,male,posterior torso,3.40,TBP tile: close-up,3D: XP,22.575830,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,99.804040
3,ISIC_0015902,0,IP_4111386,65.0,male,anterior torso,3.22,TBP tile: close-up,3D: XP,14.242329,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,99.989998
4,ISIC_0024200,0,IP_8313778,55.0,male,anterior torso,2.73,TBP tile: close-up,3D: white,24.725520,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,70.442510

In [7]:
train_metadados.head()

shape: (5, 55)
┌────────────┬────────┬────────────┬────────────┬───┬────────┬────────────┬────────────┬───────────┐
│ isic_id    ┆ target ┆ patient_id ┆ age_approx ┆ … ┆ iddx_5 ┆ mel_mitoti ┆ mel_thick_ ┆ tbp_lv_dn │
│ ---        ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---    ┆ c_index    ┆ mm         ┆ n_lesion_ │
│ str        ┆ i64    ┆ str        ┆ str        ┆   ┆ str    ┆ ---        ┆ ---        ┆ confidenc │
│            ┆        ┆            ┆            ┆   ┆        ┆ str        ┆ str        ┆ e         │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ f64       │
╞════════════╪════════╪════════════╪════════════╪═══╪════════╪════════════╪════════════╪═══════════╡
│ ISIC_00156 ┆ 0      ┆ IP_1235828 ┆ 60         ┆ … ┆        ┆            ┆ NA         ┆ 97.517282 │
│ 70         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_8170065 ┆ 60         ┆ … ┆        ┆            ┆ NA         ┆ 3.141455  │
│ 45         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_6724798 ┆ 60         ┆ … ┆        ┆            ┆ NA         ┆ 99.80404  │
│ 64         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00159 ┆ 0      ┆ IP_4111386 ┆ 65         ┆ … ┆        ┆            ┆ NA         ┆ 99.989998 │
│ 02         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00242 ┆ 0      ┆ IP_8313778 ┆ 55         ┆ … ┆        ┆            ┆ NA         ┆ 70.44251  │
│ 00         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
└────────────┴────────┴────────────┴────────────┴───┴────────┴────────────┴────────────┴───────────┘

In [8]:
tam_polars = train_metadados.estimated_size() / (1024 ** 2)
print(f"RAM consumida pelo DataFrame no Polars: {tam_polars:.2f} MB")

RAM consumida pelo DataFrame no Polars: 169.83 MB

In [9]:
tam_pandas = train_metadados_pd.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"RAM consumida pelo DataFrame no Pandas: {tam_pandas:.2f} MB")

RAM consumida pelo DataFrame no Pandas: 511.97 MB

Uma diferença um tanto quanto ignorante.

In [10]:
# limpando a memoria
del tam_pandas, train_metadados_pd

# 2.EDA

In [11]:
# vou testar o metodo lazy do polars nesse projeto
train_metadados = pl.scan_csv(
    RAW_DATA_DIR / 'train-metadata.csv',
    null_values = ["", "NA", "NAN", "N/A", "null", "None"])

## 2.1.Visão Geral

In [12]:
train_metadados.head().collect()

shape: (5, 55)
┌────────────┬────────┬────────────┬────────────┬───┬────────┬────────────┬────────────┬───────────┐
│ isic_id    ┆ target ┆ patient_id ┆ age_approx ┆ … ┆ iddx_5 ┆ mel_mitoti ┆ mel_thick_ ┆ tbp_lv_dn │
│ ---        ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---    ┆ c_index    ┆ mm         ┆ n_lesion_ │
│ str        ┆ i64    ┆ str        ┆ i64        ┆   ┆ str    ┆ ---        ┆ ---        ┆ confidenc │
│            ┆        ┆            ┆            ┆   ┆        ┆ str        ┆ str        ┆ e         │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆ f64       │
╞════════════╪════════╪════════════╪════════════╪═══╪════════╪════════════╪════════════╪═══════════╡
│ ISIC_00156 ┆ 0      ┆ IP_1235828 ┆ 60         ┆ … ┆ null   ┆ null       ┆ null       ┆ 97.517282 │
│ 70         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_8170065 ┆ 60         ┆ … ┆ null   ┆ null       ┆ null       ┆ 3.141455  │
│ 45         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00158 ┆ 0      ┆ IP_6724798 ┆ 60         ┆ … ┆ null   ┆ null       ┆ null       ┆ 99.80404  │
│ 64         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00159 ┆ 0      ┆ IP_4111386 ┆ 65         ┆ … ┆ null   ┆ null       ┆ null       ┆ 99.989998 │
│ 02         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
│ ISIC_00242 ┆ 0      ┆ IP_8313778 ┆ 55         ┆ … ┆ null   ┆ null       ┆ null       ┆ 70.44251  │
│ 00         ┆        ┆            ┆            ┆   ┆        ┆            ┆            ┆           │
└────────────┴────────┴────────────┴────────────┴───┴────────┴────────────┴────────────┴───────────┘

In [13]:
# qtd linhas do df
qtd_linhas = train_metadados.select(pl.len()).collect().item()
print(f'Número de linhas do dataframe: {qtd_linhas} linhas.')

Número de linhas do dataframe: 401059 linhas.

In [14]:
# contagem de tipos
print('Tipos dos dados: ')
Counter(list(train_metadados.collect_schema().values()))

Tipos dos dados:

Counter({Float64: 33, String: 19, Int64: 3})

In [34]:
print('Distribuicao de nulos do Dataset:')
nulos = fe.pl_dist_nulos(train_metadados)
nulos

Distribuicao de nulos do Dataset:

shape: (10, 3)
┌─────────────────────┬───────────┬───────────────┐
│ variaveis           ┆ qtd_nulos ┆ percent_nulos │
│ ---                 ┆ ---       ┆ ---           │
│ str                 ┆ u32       ┆ f64           │
╞═════════════════════╪═══════════╪═══════════════╡
│ iddx_5              ┆ 401058    ┆ 100.0         │
│ mel_mitotic_index   ┆ 401006    ┆ 99.99         │
│ mel_thick_mm        ┆ 400996    ┆ 99.98         │
│ iddx_4              ┆ 400508    ┆ 99.86         │
│ iddx_3              ┆ 399994    ┆ 99.73         │
│ iddx_2              ┆ 399991    ┆ 99.73         │
│ lesion_id           ┆ 379001    ┆ 94.5          │
│ sex                 ┆ 11517     ┆ 2.87          │
│ anatom_site_general ┆ 5756      ┆ 1.44          │
│ age_approx          ┆ 2798      ┆ 0.7           │
└─────────────────────┴───────────┴───────────────┘

Não irei me aprofundar na análise de nulos para esse projeto, portanto, apenas irei optar por excluir as colunas com mais de 40% dos valores nulos.

In [17]:
# extraindo colunas com muitos nulos
cols_null_drop = (
    nulos
        .filter(pl.col('percent_nulos') >= 40)
        .get_column('variaveis')
        .to_list()
)

print(cols_null_drop)

['iddx_5', 'mel_mitotic_index', 'mel_thick_mm', 'iddx_4', 'iddx_3', 'iddx_2', 'lesion_id']

In [18]:
# estatistica do df
train_metadados.describe()

shape: (9, 56)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ isic_id   ┆ target   ┆ patient_i ┆ … ┆ iddx_5    ┆ mel_mitot ┆ mel_thick ┆ tbp_lv_dn │
│ ---       ┆ ---       ┆ ---      ┆ d         ┆   ┆ ---       ┆ ic_index  ┆ _mm       ┆ n_lesion_ │
│ str       ┆ str       ┆ f64      ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ confidenc │
│           ┆           ┆          ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ e         │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 401059    ┆ 401059.0 ┆ 401059    ┆ … ┆ 1         ┆ 53        ┆ 63        ┆ 401059.0  │
│ null_coun ┆ 0         ┆ 0.0      ┆ 0         ┆ … ┆ 401058    ┆ 401006    ┆ 400996    ┆ 0.0       │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ 0.00098  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 97.162204 │
│ std       ┆ null      ┆ 0.031288 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 8.995782  │
│ min       ┆ ISIC_0015 ┆ 0.0      ┆ IP_000882 ┆ … ┆ Blue      ┆ 0/mm^2    ┆ 0.2       ┆ 1.2611e-1 │
│           ┆ 670       ┆          ┆ 1         ┆   ┆ nevus,    ┆           ┆           ┆ 6         │
│           ┆           ┆          ┆           ┆   ┆ Cellular  ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ 0.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 99.66883  │
│ 50%       ┆ null      ┆ 0.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 99.994588 │
│ 75%       ┆ null      ┆ 0.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 99.99996  │
│ max       ┆ ISIC_9999 ┆ 1.0      ┆ IP_998998 ┆ … ┆ Blue      ┆ >4/mm^2   ┆ 5         ┆ 100.0     │
│           ┆ 967       ┆          ┆ 9         ┆   ┆ nevus,    ┆           ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ Cellular  ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## 2.2.Análises Univariadas

In [19]:
# checando dist da coluna target
fe.pl_contagem_valores(train_metadados, 'target', excluir_na=False).collect()

shape: (2, 3)
┌────────┬────────────┬────────────────┐
│ target ┆ qtd_target ┆ percent_target │
│ ---    ┆ ---        ┆ ---            │
│ i64    ┆ u32        ┆ f64            │
╞════════╪════════════╪════════════════╡
│ 1      ┆ 393        ┆ 0.1            │
│ 0      ┆ 400666     ┆ 99.9           │
└────────┴────────────┴────────────────┘

Temos um problema extremamente desbalanceado.

In [20]:
# checando distribuicao da coluna sex
fe.pl_contagem_valores(train_metadados, 'sex', excluir_na=False).collect()

shape: (3, 3)
┌────────┬─────────┬─────────────┐
│ sex    ┆ qtd_sex ┆ percent_sex │
│ ---    ┆ ---     ┆ ---         │
│ str    ┆ u32     ┆ f64         │
╞════════╪═════════╪═════════════╡
│ null   ┆ 11517   ┆ 2.87        │
│ female ┆ 123996  ┆ 30.92       │
│ male   ┆ 265546  ┆ 66.21       │
└────────┴─────────┴─────────────┘

In [21]:
# describe da idade
df_idade_train = train_metadados.select(pl.col('age_approx'))
df_idade_train.describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ age_approx │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 398261.0   │
│ null_count ┆ 2798.0     │
│ mean       ┆ 58.012986  │
│ std        ┆ 13.596165  │
│ min        ┆ 5.0        │
│ 25%        ┆ 50.0       │
│ 50%        ┆ 60.0       │
│ 75%        ┆ 70.0       │
│ max        ┆ 85.0       │
└────────────┴────────────┘

Temos um coeficiente de variação (std / mean) de aproximadamente 23.5%, o que indica uma alta variabilidade nos dados. Irei plotar um histograma para compreender melhor essa variável, mas espero uma curva a esquerda.

In [22]:
# plotagem
(
    alt.Chart(df_idade_train.collect())
    .mark_bar()
    .encode(
        x=alt.X("age_approx", title="Idade").bin(maxbins=20),
        y=alt.Y("count()", title="Quantidade"),
    )
    .properties(width=600, height=400, title="Distribuição de Idade")
)

alt.Chart(...)

Nossa base de dados está concentrada principalmente no público entre 50 e 70 anos, o que pode enviesar nosso modelo. Ao cruzar essa variável com a target, precisarei verificar seu poder preditivo afim de pensar em como tratar esse problema.

In [23]:
train_metadados.select(pl.all().n_unique()).collect()

shape: (1, 55)
┌─────────┬────────┬────────────┬────────────┬───┬────────┬─────────────┬─────────────┬────────────┐
│ isic_id ┆ target ┆ patient_id ┆ age_approx ┆ … ┆ iddx_5 ┆ mel_mitotic ┆ mel_thick_m ┆ tbp_lv_dnn │
│ ---     ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---    ┆ _index      ┆ m           ┆ _lesion_co │
│ u32     ┆ u32    ┆ u32        ┆ u32        ┆   ┆ u32    ┆ ---         ┆ ---         ┆ nfidence   │
│         ┆        ┆            ┆            ┆   ┆        ┆ u32         ┆ u32         ┆ ---        │
│         ┆        ┆            ┆            ┆   ┆        ┆             ┆             ┆ u32        │
╞═════════╪════════╪════════════╪════════════╪═══╪════════╪═════════════╪═════════════╪════════════╡
│ 401059  ┆ 2      ┆ 1042       ┆ 17         ┆ … ┆ 2      ┆ 8           ┆ 20          ┆ 131480     │
└─────────┴────────┴────────────┴────────────┴───┴────────┴─────────────┴─────────────┴────────────┘

In [24]:
valores_unicos = (
    train_metadados
        .select(pl.all().n_unique())
        .unpivot(variable_name='variaveis', value_name='qtd_valores_unicos')
        .sort('qtd_valores_unicos', descending=False)
    ).collect()
valores_unicos

shape: (55, 2)
┌────────────────────┬────────────────────┐
│ variaveis          ┆ qtd_valores_unicos │
│ ---                ┆ ---                │
│ str                ┆ u32                │
╞════════════════════╪════════════════════╡
│ image_type         ┆ 1                  │
│ target             ┆ 2                  │
│ tbp_tile_type      ┆ 2                  │
│ iddx_5             ┆ 2                  │
│ sex                ┆ 3                  │
│ …                  ┆ …                  │
│ tbp_lv_deltaLBnorm ┆ 396877             │
│ tbp_lv_deltaA      ┆ 398257             │
│ tbp_lv_x           ┆ 398446             │
│ tbp_lv_deltaB      ┆ 398886             │
│ isic_id            ┆ 401059             │
└────────────────────┴────────────────────┘

image_type também pode ser dropada.

In [25]:
train_metadados.select(pl.col('image_type')).unique().collect()

shape: (1, 1)
┌────────────────────┐
│ image_type         │
│ ---                │
│ str                │
╞════════════════════╡
│ TBP tile: close-up │
└────────────────────┘

In [26]:
train_metadados.select(pl.col('tbp_tile_type')).unique().collect()

shape: (2, 1)
┌───────────────┐
│ tbp_tile_type │
│ ---           │
│ str           │
╞═══════════════╡
│ 3D: white     │
│ 3D: XP        │
└───────────────┘

In [27]:
train_metadados.select(pl.col('copyright_license')).unique().collect()

shape: (3, 1)
┌───────────────────┐
│ copyright_license │
│ ---               │
│ str               │
╞═══════════════════╡
│ CC-BY-NC          │
│ CC-BY             │
│ CC-0              │
└───────────────────┘

In [28]:
train_metadados.select(pl.col('attribution')).unique().collect()

shape: (7, 1)
┌─────────────────────────────────┐
│ attribution                     │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ University Hospital of Basel    │
│ ACEMID MIA                      │
│ ViDIR Group, Department of Der… │
│ Memorial Sloan Kettering Cance… │
│ Department of Dermatology, Uni… │
│ Frazer Institute, The Universi… │
│ Department of Dermatology, Hos… │
└─────────────────────────────────┘

As variáveis: tbp_lv_x, tbp_lv_y, tbp_lv_z fornecem a posição exata da lesão e isso depende muito da estatura do paciente. 

Para inserir a localização na aprendizagem do modelo, irei trabalhar com outras variáveis, as categóricas: anatom_site_general, tbp_lv_location ou tbp_lv_location_simple.

## 2.3.Data Cleaning

In [51]:
## DROPANDO COLUNAS NULAS E NAO PREDITIVAS
# selecionando as colunas a serem dropadas
columns_to_drop = [
    'tbp_lv_x', 'tbp_lv_y', 'tbp_lv_z',  # vars de posicao  (nao preditivas tambem)
    'attribution', 'copyright_license', 'image_type',  # nao preditivas
    # 'anatom_site_general', 'sex'
      
] + cols_null_drop # nulas

# dropando
df_clean = train_metadados.drop(columns_to_drop)
print(f'Colunas dropadas: {columns_to_drop}')

Colunas dropadas: ['tbp_lv_x', 'tbp_lv_y', 'tbp_lv_z', 'attribution', 'copyright_license', 'image_type', 'iddx_5', 'mel_mitotic_index', 'mel_thick_mm', 'iddx_4', 'iddx_3', 'iddx_2', 'lesion_id']

In [ ]:
# calculando quantos registros de target 1 
# perderemos em caso de exclusao de alguns nulos

# calculando qtd de target 1 no dataset de treino
col_nul = ['sex', 'anatom_site_general', 'age_approx']
qtd_target_1_geral = fe.pl_contagem_valores(train_metadados, 'target').filter(pl.col('target') == 1).select('qtd_target').collect().item()

# calculo de perda
for c in col_nul:
    aux = df_clean.filter(~pl.col(c).is_null())
    qtd_target_1_filtrado = (
        fe.pl_contagem_valores(aux, 'target')  # calculando qtd de target 1
            .filter(pl.col('target') == 1)
            .select('qtd_target')
            .collect()
            .item()
        )
    perdidos = qtd_target_1_geral - qtd_target_1_filtrado
    prop_perdidos = perdidos / qtd_target_1_geral
    print(f'Excluindo nulos de {c} perderemos {perdidos} ({prop_perdidos:.2%}) registros de target = 1.')

Excluindo nulos de sex perderemos 10 (2.54%) registros de target = 1.
Excluindo nulos de anatom_site_general perderemos 0 (0.00%) registros de target = 1.
Excluindo nulos de age_approx perderemos 3 (0.76%) registros de target = 1.

Por se tratar de um problema desbalanceado, irei preservar ao máximo a quantidade de registros de target = 1. Portanto, irei preencher sex com a moda e idade com a mediana.

Irei dropar os registros sem anatom_site_general pois pode ser perigoso inferir o local da lesão tanto para o aprendizado do modelo quanto para o paciente.

# Lembrar de preencher os nulos e salvar os valores que serão usados para preencher esses nulos em um .json para poder inserir posteriormente na pipeline final.

## 2.3.Analise Bivariada

In [31]:
# amostrando para analises
mdt_sample = train_metadados.collect().sample(fraction=0.25)
qtd_linhas = mdt_sample.select(pl.col('target')).count().item()
print(f'Dataframe de treino amostrado em 25% resultou em: {qtd_linhas} linhas.')

Dataframe de treino amostrado em 25% resultou em: 100264 linhas.

In [32]:
for t in [0, 1]:
    df_aux = mdt_sample.filter(pl.col('target') == t)
    graf = (
        alt.Chart(df_aux)
        .mark_bar()
        .encode(
            x=alt.X("age_approx", title="Idade").bin(maxbins=20),
            y=alt.Y("count()", title="Quantidade"),
        )
        .properties(width=400, height=200, title=f"Distribuição de Idade com Target = {t}")
    )
    graf.show()

alt.Chart(...)

alt.Chart(...)

In [33]:
float_vars = (
    mdt_sample
    .select(vars_preditivas, cs.float())
    .collect_schema()
    .names()
)[1:]

NameError: name 'vars_preditivas' is not defined

In [ ]:
# amostrando dados para correlacao
#mdt_sample = df_mdt.select(float_vars).collect().sample(fraction=0.15)
#print(f'A amostragem foi feita usando 15% dos dados, o que resultou em: {mdt_sample["target"].count()} linhas.')

# calculando correlacao
df_corr = mdt_sample.select(float_vars).corr()
# del df_mdt_sample

In [ ]:
df_corr

shape: (33, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ clin_size ┆ tbp_lv_A  ┆ tbp_lv_Ae ┆ tbp_lv_B  ┆ … ┆ tbp_lv_x ┆ tbp_lv_y  ┆ tbp_lv_z  ┆ tbp_lv_dn │
│ _long_dia ┆ ---       ┆ xt        ┆ ---       ┆   ┆ ---      ┆ ---       ┆ ---       ┆ n_lesion_ │
│ m_mm      ┆ f64       ┆ ---       ┆ f64       ┆   ┆ f64      ┆ f64       ┆ f64       ┆ confidenc │
│ ---       ┆           ┆ f64       ┆           ┆   ┆          ┆           ┆           ┆ e         │
│ f64       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 1.0       ┆ -0.040503 ┆ -0.074403 ┆ -0.116835 ┆ … ┆ 0.00441  ┆ 0.022439  ┆ -0.009722 ┆ -0.075041 │
│ -0.040503 ┆ 1.0       ┆ 0.759606  ┆ 0.413784  ┆ … ┆ 0.011007 ┆ 0.218791  ┆ 0.028799  ┆ 0.147533  │
│ -0.074403 ┆ 0.759606  ┆ 1.0       ┆ 0.243284  ┆ … ┆ 0.018571 ┆ 0.204062  ┆ 0.05154   ┆ -0.02525  │
│ -0.116835 ┆ 0.413784  ┆ 0.243284  ┆ 1.0       ┆ … ┆ 0.001401 ┆ 0.31395   ┆ 0.097588  ┆ 0.230464  │
│ -0.036279 ┆ 0.48838   ┆ 0.355481  ┆ 0.90997   ┆ … ┆ 0.001933 ┆ 0.315817  ┆ 0.117655  ┆ 0.158634  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 0.024836  ┆ -0.071443 ┆ 0.210842  ┆ -0.06077  ┆ … ┆ 0.004391 ┆ -0.004789 ┆ -0.001596 ┆ -0.279316 │
│ 0.00441   ┆ 0.011007  ┆ 0.018571  ┆ 0.001401  ┆ … ┆ 1.0      ┆ 0.004614  ┆ -0.00999  ┆ -0.0082   │
│ 0.022439  ┆ 0.218791  ┆ 0.204062  ┆ 0.31395   ┆ … ┆ 0.004614 ┆ 1.0       ┆ -0.012851 ┆ 0.069038  │
│ -0.009722 ┆ 0.028799  ┆ 0.05154   ┆ 0.097588  ┆ … ┆ -0.00999 ┆ -0.012851 ┆ 1.0       ┆ 0.051411  │
│ -0.075041 ┆ 0.147533  ┆ -0.02525  ┆ 0.230464  ┆ … ┆ -0.0082  ┆ 0.069038  ┆ 0.051411  ┆ 1.0       │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [ ]:
df_corr

shape: (36, 36)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ target    ┆ age_appro ┆ clin_size ┆ tbp_lv_A  ┆ … ┆ tbp_lv_x  ┆ tbp_lv_y ┆ tbp_lv_z  ┆ tbp_lv_dn │
│ ---       ┆ x         ┆ _long_dia ┆ ---       ┆   ┆ ---       ┆ ---      ┆ ---       ┆ n_lesion_ │
│ f64       ┆ ---       ┆ m_mm      ┆ f64       ┆   ┆ f64       ┆ f64      ┆ f64       ┆ confidenc │
│           ┆ f64       ┆ ---       ┆           ┆   ┆           ┆          ┆           ┆ e         │
│           ┆           ┆ f64       ┆           ┆   ┆           ┆          ┆           ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1.0       ┆ NaN       ┆ 0.026383  ┆ 0.015324  ┆ … ┆ 0.005463  ┆ 0.010587 ┆ -0.009622 ┆ -0.056261 │
│ NaN       ┆ NaN       ┆ NaN       ┆ NaN       ┆ … ┆ NaN       ┆ NaN      ┆ NaN       ┆ NaN       │
│ 0.026383  ┆ NaN       ┆ 1.0       ┆ -0.041073 ┆ … ┆ 0.004337  ┆ 0.022501 ┆ -0.006252 ┆ -0.078121 │
│ 0.015324  ┆ NaN       ┆ -0.041073 ┆ 1.0       ┆ … ┆ 0.014259  ┆ 0.217359 ┆ 0.033455  ┆ 0.145998  │
│ 0.019001  ┆ NaN       ┆ -0.07052  ┆ 0.756395  ┆ … ┆ 0.018014  ┆ 0.201528 ┆ 0.05275   ┆ -0.028333 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 0.006737  ┆ NaN       ┆ 0.005423  ┆ 0.001362  ┆ … ┆ 0.00399   ┆ 0.000842 ┆ -0.004241 ┆ -0.007936 │
│ 0.005463  ┆ NaN       ┆ 0.004337  ┆ 0.014259  ┆ … ┆ 1.0       ┆ 0.004775 ┆ -0.006198 ┆ -0.005125 │
│ 0.010587  ┆ NaN       ┆ 0.022501  ┆ 0.217359  ┆ … ┆ 0.004775  ┆ 1.0      ┆ -0.00843  ┆ 0.073889  │
│ -0.009622 ┆ NaN       ┆ -0.006252 ┆ 0.033455  ┆ … ┆ -0.006198 ┆ -0.00843 ┆ 1.0       ┆ 0.050285  │
│ -0.056261 ┆ NaN       ┆ -0.078121 ┆ 0.145998  ┆ … ┆ -0.005125 ┆ 0.073889 ┆ 0.050285  ┆ 1.0       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

# lembrar de cruzar idade com a target!!!

In [ ]:
(13.596165 / 58.012986)*100

23.43641646027322

In [ ]:
13.596165 / 58.012986 * 100

23.43641646027322